apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "backend.fullname" . }}

data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
  DB_HOST: {{ .Values.config.database.host | quote }}
  DB_PORT: {{ .Values.config.database.port | quote }}
  DB_NAME: {{ .Values.config.database.name | quote }}