apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
  SPRING_DATASOURCE_URL: "jdbc:aws-wrapper:postgresql://{{ .Values.config.database.host }}:{{ .Values.config.database.port }}/{{ .Values.config.database.name }}?wrapperPlugins=iam"
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.database.username | quote }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "software.amazon.jdbc.Driver"
  AWS_REGION: "us-east-1"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SERVER_PORT: "8081"