{{- if .Values.config.dbInitHook }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backend.fullname" . }}-db-init
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: postgres:16-alpine
          env:
            - name: PGPASSWORD
              value: {{ required "DB_PASSWORD: DB_PASSWORD" .Values.config.database.adminPassword | quote }}
          command:
            - sh
            - -c
            - |
              psql \
              -h {{ .Values.config.database.host }} \
              -U {{ .Values.config.database.adminUsername }} \
              -d {{ .Values.config.database.name }} <<EOF

              DO \$\$
              BEGIN
                IF NOT EXISTS (
                  SELECT FROM pg_roles 
                  WHERE rolname = 'backend_app'
                ) THEN
                  CREATE USER backend_app;
                END IF;
              END
              \$\$;

              GRANT rds_iam TO backend_app;

              GRANT CONNECT
              ON DATABASE {{ .Values.config.database.name | quote }}
              TO backend_app;

              GRANT USAGE, CREATE
              ON SCHEMA public
              TO backend_app;

              GRANT ALL PRIVILEGES
              ON ALL TABLES IN SCHEMA public
              TO backend_app;

              GRANT ALL PRIVILEGES
              ON ALL SEQUENCES
              IN SCHEMA public
              TO backend_app;

              ALTER DEFAULT PRIVILEGES
              IN SCHEMA public
              GRANT ALL ON TABLES TO backend_app;

              ALTER DEFAULT PRIVILEGES
              IN SCHEMA public
              GRANT ALL ON SEQUENCES TO backend_app;

              EOF
{{- end }}