apiVersion: v1
kind: Secret

metadata:
  name: {{ include "backend.fullname" . }}

type: Opaque

stringData:
  DB_USERNAME: {{ .Values.secret.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}