apiVersion: v1
kind: Secret

metadata:
  name: {{ include "backend.fullname" . }}

type: Opaque

stringData:
  JWT_SECRET: {{ required "JWT_SECRET: JWT_SECRET" .Values.secret.jwtSecret | quote }}

  POSTGRES_PASSWORD: {{ required "DB_PASSWORD: DB_PASSWORD" .Values.config.database.adminPassword | quote }}