apiVersion: v1
kind: Secret

metadata:
  name: {{ include "backend.fullname" . }}

type: Opaque

stringData:
  POSTGRES_PASSWORD: {{ required "DB_PASSWORD: DB_PASSWORD" .Values.config.database.adminPassword | quote }}