replicaCount: 1

image:
  repository: 071540691508.dkr.ecr.us-east-1.amazonaws.com/dev-eks-cluster-dev-ecr-repo
  tag: backend-242ed56
  pullPolicy: IfNotPresent
imagePullSecrets: []

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

config:
  dbInitHook: true
  springProfile: prod
  database:
    host: dev-eks-cluster-postgres.ckhkeogg21ln.us-east-1.rds.amazonaws.com
    port: 5432
    name: bookstore
    adminUsername: postgres
    adminPassword: ""
    username: backend_app

serviceAccount:
  create: true
  name: backend-sa
  roleArn: "arn:aws:iam::715736407442:role/dev-eks-cluster-backend-irsa"  
  annotations: {}
#aws iam list-open-id-connect-providers
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

podSecurityContext:
  fsGroup: 1000
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
autoscaling:
  enabled: false

serviceMonitor:
  enabled: true