version: '3.8'

services:
  frontend:
    image: drilonnol/frontendd:latest
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - mynet

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
    networks:
      - mynet

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    networks:
      - mynet

networks:
  mynet:
