global:
  environment: production


backend:
  enabled: true

frontend:
  enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: {}    

  paths:
    frontend:
      service: bookstore-frontend
      port: 80
    backend:
      service: bookstore-backend
      port: 8081